stages:
  - build
  - deploy

build:
  image: docker:stable
  services:
    - docker:dind
  stage: build
  script:
    - docker login -u "$REGISTRY_USERNAME" -p "$REGISTRY_PASSWORD" "$REGISTRY_SERVERNAME"
    - docker build -t $REGISTRY_SERVERNAME/rubysampleapp:$CI_COMMIT_SHA .
    - docker push $REGISTRY_SERVERNAME/rubysampleapp:$CI_COMMIT_SHA

deploy:
  image: mcr.microsoft.com/azure-cli
  stage: deploy
  script: 
    - az login --service-principal --username "$AZURE_CLIENT_ID" --password "$AZURE_CLIENT_SECRET" --tenant "$AZURE_TENANT_ID"
    - az account set --subscription "$AZURE_SUBSCRIPTION_ID"
    - az extension add -n containerapp
    - az containerapp create --name testrubyapp12 --resource-group POC-RG --environment test-env
      --registry-password $REGISTRY_PASSWORD --registry-server $REGISTRY_SERVERNAME --registry-username $REGISTRY_USERNAME
      --target-port 8080 --ingress external
      --image "$REGISTRY_SERVERNAME/rubysampleapp:$CI_COMMIT_SHA"
